CREATE TABLE noticia (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     image VARCHAR(500),
     title VARCHAR(255),
     date TIMESTAMP WITH TIME ZONE,
     short_description TEXT,
     slug VARCHAR(100) UNIQUE,
     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_noticia_date ON noticia(date);
CREATE INDEX idx_noticia_slug ON noticia(slug);
CREATE INDEX idx_noticia_created_at ON noticia(created_at);

CREATE TABLE noticia_conteudo (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      noticia_id BIGINT REFERENCES noticia(id) ON DELETE CASCADE,
      long_description TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_noticia_conteudo_noticia_id ON noticia_conteudo(noticia_id);
CREATE UNIQUE INDEX idx_noticia_conteudo_unique ON noticia_conteudo(noticia_id);