CREATE TABLE projeto (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   description TEXT,
   cover VARCHAR(1024),
   short_description TEXT,
   slug VARCHAR(255) NOT NULL UNIQUE,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO projeto (title, description, cover, short_description, slug) VALUES
('Projeto 1', 'Descrição do projeto 1', 'https://picsum.photos/370/320?random=1', 'Apoio e informação para pessoas com esclerose múltipla.', 'projeto-1'),
('Projeto 2', 'Descrição do projeto 2', 'https://picsum.photos/370/320?random=2', 'Campanhas de conscientização sobre esclerose múltipla.', 'projeto-2'),
('Rifa Solidária', 'Participe da nossa rifa solidária e ajude nossa causa!', 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=370&q=80', 'Escolha um número e concorra a prêmios ajudando nossa ONG.', 'rifa');

