CREATE TABLE evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    imagem VARCHAR(500),
    local VARCHAR(255),
    data_inicio TIMESTAMP WITH TIME ZONE,
    data_fim TIMESTAMP WITH TIME ZONE,
    inicio_inscricoes TIMESTAMP WITH TIME ZONE,
    fim_inscricoes TIMESTAMP WITH TIME ZONE,
    limite_inscricoes INTEGER,
    status VARCHAR(30) NOT NULL DEFAULT 'RASCUNHO',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_evento_status ON evento(status);
CREATE INDEX idx_evento_data_inicio ON evento(data_inicio);

CREATE TABLE evento_campo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL REFERENCES evento(id),
    label VARCHAR(255) NOT NULL,
    chave VARCHAR(100) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    obrigatorio BOOLEAN NOT NULL DEFAULT FALSE,
    unico BOOLEAN NOT NULL DEFAULT FALSE,
    ordem INTEGER NOT NULL DEFAULT 0,
    placeholder VARCHAR(255),
    texto_ajuda VARCHAR(255),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX idx_evento_campo_evento_chave ON evento_campo(evento_id, chave);
CREATE INDEX idx_evento_campo_evento_ordem ON evento_campo(evento_id, ordem);

CREATE TABLE evento_campo_opcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campo_id BIGINT NOT NULL REFERENCES evento_campo(id) ON DELETE CASCADE,
    label VARCHAR(255) NOT NULL,
    valor VARCHAR(255) NOT NULL,
    ordem INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_evento_campo_opcao_valor ON evento_campo_opcao(campo_id, valor);
CREATE INDEX idx_evento_campo_opcao_ordem ON evento_campo_opcao(campo_id, ordem);

CREATE TABLE evento_inscricao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL REFERENCES evento(id),
    status VARCHAR(30) NOT NULL DEFAULT 'CONFIRMADA',
    nome_inscrito VARCHAR(255),
    email_inscrito VARCHAR(255),
    telefone_inscrito VARCHAR(30),
    cpf_inscrito VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_evento_inscricao_evento ON evento_inscricao(evento_id);
CREATE INDEX idx_evento_inscricao_evento_status ON evento_inscricao(evento_id, status);
CREATE INDEX idx_evento_inscricao_email ON evento_inscricao(email_inscrito);
CREATE INDEX idx_evento_inscricao_cpf ON evento_inscricao(cpf_inscrito);
CREATE INDEX idx_evento_inscricao_telefone ON evento_inscricao(telefone_inscrito);
CREATE INDEX idx_evento_inscricao_created_at ON evento_inscricao(created_at);

CREATE TABLE evento_inscricao_resposta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscricao_id BIGINT NOT NULL REFERENCES evento_inscricao(id) ON DELETE CASCADE,
    campo_id BIGINT NOT NULL REFERENCES evento_campo(id),
    chave_campo VARCHAR(100) NOT NULL,
    valor_texto TEXT,
    valor_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_evento_inscricao_resposta_inscricao ON evento_inscricao_resposta(inscricao_id);
CREATE INDEX idx_evento_inscricao_resposta_campo ON evento_inscricao_resposta(campo_id);
CREATE INDEX idx_evento_inscricao_resposta_chave ON evento_inscricao_resposta(chave_campo);
CREATE INDEX idx_evento_inscricao_resposta_valor_texto ON evento_inscricao_resposta(campo_id, valor_texto);
